# planner:
#   ros__parameters:
#     max_v: 50.0
#     max_a: 50.0

#     waypoint_names: ["p0", "p1", "p2", "p1", "p0"] # To the first lantern

#     waypoints: # To the first lantern
#       p0:
#         pos: [-80.0, 10.0, 7.0]
#       p1:
#         pos: [-80.0, 0.0, 7.0]
#       p2:
#         pos: [-80.0, -10.0, 7.0]
  
  ros__parameters:
    max_v: 5.0
    max_a: 10.0

    waypoint_names: ["p1", "p2", "p3", "p4", "p5"] # To the cave entrance

    waypoints: # To the cave entrance
      p1:
        pos: [-50.0, 10.0, 10.0]
      p2:
        pos: [-100.0, 10.0, 12.0]
      p3:
        pos: [-150.0, 10.0, 14.0]
      p4:
        pos: [-200.0, 10.0, 16.0]
      p5:
        pos: [-250.0, 10.0, 18.0]
      p6:
        pos: [-300.0, 10.0, 18.0]