planner:
  ros__parameters:
    max_v: 15.0
    max_a: 20.0

    # waypoint_names: ["p1","p2","p3","p4","p5", "t1","t1_2","t2","t3","t4",  "p1","p1_2","p2","p3","p4","p5", "t1","t1_2","t2_s","t3","t4"]
    waypoint_names: ["p1"]

    waypoints:
      p0:
        pos: [-38.0, 10.0, 12.0]
      p1:
        pos: [-28.0, 10.0, 9.5]
      p1_2:
        pos: [-23.0, 10.0, 9.5]
      p2:
        pos: [-8.0, 20.0, 9.5]
      p3:
        pos: [-3.0, 35.0, 19.5]
      p4:
        pos: [-3.0, 45.0, 12.5]
      p5:
        pos: [-13.0, 49.0, 17.5]
      t1:
        pos: [-22.0, 49.0, 17.5]
      t1_2:
        pos: [-24.0, 49.0, 17.5]
      t2:
        pos: [-27.0, 49.0, 17.5]
      t3:
        pos: [-32.0, 49.0, 17.5]
      t4:
        pos: [-34.0, 49.0, 17.5]
      t2_s:
        pos: [-27.0, 49.0, 17.5]
        vel: [0.0, 0.0, 0.0]
        acc: [0.0, 0.0, 0.0]
