planner:
  ros__parameters:
    max_v: 15.0
    max_a: 20.0

    waypoint_names: ["p1","p2","p3","p4","p5", "t1","t1_2","t2","t3","t4",  "p0","p1","p1_2","p2","p3","p4","p5", "t1","t1_2","t2_s","t3","t4"]

    waypoints:
      p0:
        pos: [2.0, 10.0, 3.0]
      p1:
        pos: [10.0, 0.0, 3.0]
      p1_2:
        pos: [15.0, 0.0, 3.0]
      p2:
        pos: [30.0, 10.0, 3.0]
      p3:
        pos: [35.0, 25.0, 13.0]
      p4:
        pos: [35.0, 35.0, 6.0]
      p5:
        pos: [25.0, 39.0, 11.0]
      t1:
        pos: [16.0, 39.0, 11.0]
      t1_2:
        pos: [14.0, 39.0, 11.0]
      t2:
        pos: [11.0, 39.0, 11.0]
      t3:
        pos: [6.0, 39.0, 11.0]
      t4:
        pos: [4.0, 39.0, 11.0]
      t2_s:
        pos: [11.0, 39.0, 11.0]
        vel: [0.0, 0.0, 0.0]
        acc: [0.0, 0.0, 0.0]
